### ISSUE TITLE
使用查询排名功能时,群内未接受到消息

### ISSUE THREAD

**Issue by PalenCent** [zyujs/clanbattle_rank#1]
环境:mirai + hoshinobotv2
问题:群内未接收到推送的消息
见下图
![image](https://user-images.githubusercontent.com/45139699/92379038-56ce1e00-f139-11ea-9197-df7f3f430438.png)
![image](https://user-images.githubusercontent.com/45139699/92379073-664d6700-f139-11ea-892f-c80d38553d21.png)

**Comment by zyujs** [comment]
你号被腾讯风控了,长消息发不出.不是插件的问题,也不是mirai的问题.
