### ISSUE TITLE
关注的工会排名排版混乱

### ISSUE THREAD

**Issue by isaac1216** [zyujs/clanbattle_rank#3]
![image](https://user-images.githubusercontent.com/68545246/99379808-1b538b00-2904-11eb-87ee-7d1ffb2a7286.png)
查询关注时候排版乱了，可能是因为工会名字比较长？

![QQ图片20201117183920](https://user-images.githubusercontent.com/68545246/99379914-3a521d00-2904-11eb-87a5-906307c0c62f.png)
直接查询排名时这样，希望可以统一一下

**Comment by zyujs** [comment]
就是这样的, 为了手机端显示效果, 每一条分2行
